name: UNIX

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
on:
  push:
  pull_request:
    paths-ignore:
      - 'examples/**'
      - 'README.md'
      - 'ci/*esp32*.sh'
      - '.github/workflows/build_esp32.yml'

jobs:
  tensorflow_micropython_unix_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Pillow & Wave
        run: |
          pip install Pillow
          pip3 install Wave
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare to Build Tensorflow Micropython Firmware for UNIX
        run: |
          git submodule init
          git submodule update --recursive

      - name: Setup Build for Tensorflow
        run: |

          echo "Regenerating microlite/tfm directory"
          rm -rf ./micropython-modules/microlite/tflm

          cd ./tensorflow

          ../micropython-modules/microlite/prepare-tflm-unix.sh

      - name: Setup micropython modules
        run: |
          cd ./micropython-modules
          ln -s ../micropython-ulab/code ulab
          
      - name: Build micropython cross compiler
        run:  |
          cd ./micropython
          echo "make -C mpy-cross V=1 clean all"
          make -C mpy-cross V=1 clean all
      - name: Prepare to Build Tensorflow Micropython Firmware for unix
        run: |
          cd micropython/ports/unix
          make submodules
          make deplibs

          make VARIANT_DIR=../../../boards/unix/microlite-variant VARIANT=microlite
         
      - name: Archive Unix MICROLITE micropython interpreter
        uses: actions/upload-artifact@v2
        with:
          name: microlite-unix-micropython
          path: |
            micropython/ports/unix/micropython
